version: "3.4"

# IMPORTANT NOTE: Volume paths mounted on containers are relative to the
# directory that this file is in (`docker/`) and so probably need to start with
# `../` to refer to a directory in the main code checkout

services:

  db:
    image: postgres:9.5.3
    command: postgres -F

  redis:
    image: redis:5.0.3

  timescale:
    image: timescale/timescaledb:latest-pg11
    environment:
      POSTGRES_PASSWORD: 'postgres'

  listenbrainz:
    build:
      context: ..
      dockerfile: Dockerfile
      target: listenbrainz-dev
    command: py.test listenbrainz/tests/integration
    image: listenbrainz
    depends_on:
      - redis
      - db
      - influx
      - rabbitmq

  influx_writer:
    image: listenbrainz
    command: python3 -m "listenbrainz.influx_writer.influx_writer"
    depends_on:
      - redis
      - influx

  rabbitmq:
    image: rabbitmq:3.6.5
    ports:
      - "5672:5672"
